### ISSUE TITLE
Issue with char encoding

### ISSUE THREAD

**Issue by remk** [ochrons/scalajs-spa-tutorial#10]
Define the definition of a todo item as "é" it will appear as "Ã©".
Check or uncheck the item it will become "ÃÂ©". 
Do it once more and it will be "ÃÂÃÂ©" and so on.

Thanks for this nice tutorial !

**Comment by ochrons** [comment]
I cannot reproduce this. It works just fine with non-ASCII characters like é or ä for me.

**Comment by remk** [comment]
I reproduce this issue on safari (8.0.4).
It works fine on chrome and firefox.
The cache was cleaned on both browser.

**Comment by ochrons** [comment]
I added `application/json` content types on both requests and responses, which should fix this problem. If you can verify it on Safari (don't have OSX machine myself), that would be great.

**Comment by remk** [comment]
I've just checked it on safari. There is no encoding problem anymore.
Thanks.
