### ISSUE TITLE
Latest release crashes on win7 - GC overhead limit exceeded

### ISSUE THREAD

**Issue by larrymelia** [ochrons/scalajs-spa-tutorial#11]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\XPS3D>d:

D:>cd cyberthinkers-dev

D:\cyberthinkers-dev>cd scalajs-spa-tutorial

D:\cyberthinkers-dev\scalajs-spa-tutorial>git pull
Already up-to-date.

D:\cyberthinkers-dev\scalajs-spa-tutorial>sbt
[info] Loading global plugins from C:\Users\XPS3D.sbt\0.13\plugins
[info] Loading project definition from D:\cyberthinkers-dev\scalajs-spa-tutorial\project
[info] Set current project to SPAtutorial (in build file:/D:/cyberthinkers-dev/scalajs-spa-tutorial/)
[INFO] [04/10/2015 07:44:26.290] [Workbench-System-akka.actor.default-dispatcher-4] [akka://Workbench-System/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:13131

> re-start
> [info] Fast optimizing D:\cyberthinkers-dev\scalajs-spa-tutorial\jvm\target\scala-2.11\classes\web\js\scalajs-spa-fastopt.js
> [info] workbench: Reloading Pages...
> [info] Compiling 4 Scala sources to D:\cyberthinkers-dev\scalajs-spa-tutorial\jvm\target\scala-2.11\classes...
> [info] LESS compiling on 1 source(s)
> Uncaught error from thread [sbt-web-scheduler-1] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[sbt-web]
> [ERROR] [04/10/2015 09:10:32.028] [sbt-web-scheduler-1] [ActorSystem(sbt-web)] exception on LARSÆ timer thread
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> java.lang.OutOfMemoryError: GC overhead limit exceeded
>         at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:409)
>         at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:409)
>         at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
>         at java.lang.Thread.run(Thread.java:744)
>         at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)

```
    at java.lang.Thread.run(Thread.java:744)
```

[INFO] [04/10/2015 09:10:32.029] [sbt-web-scheduler-1] [ActorSystem(sbt-web)] starting new LARS thread

D:\cyberthinkers-dev\scalajs-spa-tutorial>

**Comment by ochrons** [comment]
You may need to allocate more memory for SBT as Scala.js compilation takes quite a bit of memory

**Comment by larrymelia** [comment]
Well, I set the memory to 2 gigs on Java 7 run-time (-XX:MaxPermSize=2048m), same problem, then I tried Java 8 with GC set to 2 gigs (-XX:MaxMetaspaceSize=2048m), same problem. This example project did work at one point, but the latest release has issues on Windows. Looks like a process is failing in Akka and it's doing a relaunch to recover. Because the prior code isn't release (bug in Akka?) the memory is exhausted after too many attempts of loading the class files. Anymore ideas on what I might try?

Thanks for taking a look at this issue.

**Comment by ochrons** [comment]
MaxPermSize is not relevant for this, you need to adjust heap size with -Xmx

I'm using Windows 8.1 myself and have -Xmx1024m in my SBT config.

The problem seems to occur in the sbt-web plugin while compiling the LESS files, so this is not really  something to be solved in the context of this tutorial project.

**Comment by larrymelia** [comment]
Thanks! That worked!

**Comment by omidb** [comment]
Hi,
I'm using win 8.1, I have the same problem, where should I exactly change to get it to work?
Thanks!

**Comment by ochrons** [comment]
I have in my `sbt/conf/sbtconfig.txt` a line that specifies the heap size (amongst other parameters)

`-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xmx2048M -Xss2M`
