### ISSUE TITLE
Don't mix RoutingRules and Router

### ISSUE THREAD

**Issue by japgolly** [ochrons/scalajs-spa-tutorial#14]
As discussed in scalajs-react gitter
1. Rename `MainRouter` to `MainRoutes`.
2. Remove `{baseUrl, router, routerComponent}` from `MainRouter`.
3. Best to create `router` at the JS entry point / init fn and pass it around as a dependency instead of accessing as a singleton.

**Comment by ochrons** [comment]
New Router2 makes this obsolete
