### ISSUE TITLE
checking a todo item creates a duplicate

### ISSUE THREAD

**Issue by bblfish** [ochrons/scalajs-spa-tutorial#17]
I added some Todos and whenever I check them as done, I get a duplicate.

![screen shot 2015-05-10 at 19 30 19](https://cloud.githubusercontent.com/assets/124506/7555415/0d4c876e-f74b-11e4-9402-aa354fb8d221.png)

My IntelliJ EAP is not able to load the project, so it's not easy to find the bug for me. Will continue reading...

**Comment by Daxten** [comment]
had the same problem and could only fix it by using a different serializer.. bug must be in the serialization / unserialization :(

**Comment by oyvindberg** [comment]
Definitely the serializer. 

Try adding a task with say content «dc651541-bb0c-476a-8de5-3e3fc319f96d», and afterwards mark is as completed. The duplicate which appears then has content «6a470cbb-4115-65dc-6df9-19c33f3ee58d», which perfectly illustrates what happens to the generated IDs. Note that its the same number, but with the bytes for each half of the UUID in reversed order.

**Comment by ochrons** [comment]
Yes, seems like a problem in byte order when encoding an UUID into special binary mode. Fixing it soon :)

**Comment by oyvindberg** [comment]
Indeed looks like byte order problem, although i found it weird that it would affect a String, hehe :)
Thanks for looking into it anyway

**Comment by oyvindberg** [comment]
Right, just had a look at boopickle - fancy stuff you got going there. If anyone wants the example running properly something like 

```
-      val newItem = item.copy(id = UUID.randomUUID().toString)
+      val newItem = item.copy(id = UUID.randomUUID().toString + 'q')
```

would do the trick for now :)
