### ISSUE TITLE
recompile frontend only?

### ISSUE THREAD

**Issue by mrmechko** [ochrons/scalajs-spa-tutorial#19]
First, thanks so much for this tutorial, I don't know what I would have done without it.

I was wondering if it is possible (or if I missed something) to recompile/re-start the front-end only.  My server-side has a relatively long start up time, so it becomes very time consuming when I'm just modifying the layout/css stuff.

**Comment by simerplaha** [comment]
you can just use "sbt ~fastOptJS" command to just work on your front end stuff and then open index.html from your js/target/scala/index.html in your browser.

Adding "re-start" to your command will start your server. Which I'm guessing you don't want.
