### ISSUE TITLE
Client source files are in the distribution assets

### ISSUE THREAD

**Issue by ochrons** [ochrons/scalajs-spa-tutorial#20]
All Scala sources for the client are included in the server distribution bundle under assets.

This is a regression in Play 2.4 and sbt-play-scalajs v0.2.6

**Comment by vmunier** [comment]
Hi @ochrons,

Upgrading to sbt-play-scalajs v0.2.7 should fix the issue. The Scala files of the client projects are not included in the final jar by default. You can set `(emitSourceMaps in fullOptJS) := true` in the Scala.js project if you want to enable sourcemaps in production (which will also include the Scala files inside the jar).
