### ISSUE TITLE
Feature request: running with npm & bower instead/with Webjar

### ISSUE THREAD

**Issue by hajime-moto** [ochrons/scalajs-spa-tutorial#21]
It will be great to see this tutorial work with NPM and Bower instead/with Webjar. Seems like a lot of dependencies are missing from webjar.org and NPM's package.json file seems to be a lot easier to configure to download JS dependencies into a project.

**Comment by mkotsbak** [comment]
Actually you can autoimport from both NPM and Bower to webjars here: http://www.webjars.org/ Then there should be no missing dependencies and no extra build system.

**Comment by ochrons** [comment]
I agree with @mkotsbak that the NPM/Bower support in WebJars is quite good for managing JS dependencies, since you can get anything through that.
