### ISSUE TITLE
NullPointerException on 0.6.6

### ISSUE THREAD

**Issue by Enalmada** [ochrons/scalajs-spa-tutorial#33]
FYI that when trying to up the project to scalajs 0.6.6 I got a null pointer issue during testing.  To save yourself some stress, you may want to hold off upgrading until this ticket is resolved:  https://github.com/scala-js/scala-js/issues/2219

**Comment by ochrons** [comment]
Ok, 0.6.7 should be out next week, so I'll postpone updating SPA until then, thanks! :)
