### ISSUE TITLE
"Zoom" vs "reader" function

### ISSUE THREAD

**Issue by mb720** [ochrons/scalajs-spa-tutorial#34]
Thanks a ton for your great tutorial!

I spotted a little inconsistency regarding the name of the function used to specify what to read from the model.
In the tutorial it's called **reader** function, for example [here](https://ochrons.github.io/scalajs-spa-tutorial/todo-module-and-data-flow.html#modifying-a-todo-state):

> Both methods take a _reader function_ that extracts the part of the model we are interested in.

But in [ReactConnector#wrap it's called **zoomFunc**.](https://github.com/ochrons/diode/blob/ece23b64e3e57ec1d6da963702885c6e3e3eeb92/diode-react/src/main/scala/diode/react/ReactConnector.scala#L35)

Thanks again for your immensely useful tutorial!

Best,
Matthias

**Comment by ochrons** [comment]
Yeah, the names can be used interchangeably in this case. It's called zoomFunc because it's used in as a parameter for the zoom function :)
