### ISSUE TITLE
How to simulate lag

### ISSUE THREAD

**Issue by mb720** [ochrons/scalajs-spa-tutorial#36]
Hi,

I was wondering how to simulate server-side delays to test "Loading..." messages on the client side.
In the tutorial I've seen that the server does `Thread.sleep(300)` a couple of times and that the client uses `proxy().renderPending(_ > 500, _ => <.p("Loading...")),`.

Somehow I expected that if I increased the time the server sleeps to, say, three seconds, that I would then see a "Loading..." message at the client but this is not the case.

Is there a way to simulate a slow or flaky internet connection between server and client while doing localhost development?

Thanks a lot in advance,
Matthias

**Comment by ochrons** [comment]
In Chrome developer tools Network panel you can simulate network throttling. That should create enough lag for these delay effects to show. Although, I haven't really tested that part of SPA tutorial, so maybe it has a bug, too :)

**Comment by ochrons** [comment]
Did you get this to work?

**Comment by mb720** [comment]
I'm confident that I can simulate lag using the browser's developer tools but I didn't try it.
