### ISSUE TITLE
SBT launch fails with error: "Unsupported Major.minor version 52.0"

### ISSUE THREAD

**Issue by gtkovas** [ochrons/scalajs-spa-tutorial#38]
Full error text: 

java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0

Forgive me if this is an obvious fix, I'm a newcomer to scala.js. Various searches indicate that I need to specify a target version of the JVM in build.sbt, but none of the solutions found elsewhere have worked in this case.

I am working from an unmodified clone of this project.

**Comment by ochrons** [comment]
You probably need to use Java8.
