### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by StefanScott** [ochrons/scalajs-spa-tutorial#6]
Thank you for this demo. It is very full-featured, and incorporates several optimal design decisions (eg, using a Flux architecture).

In particular, I'm impressed to see someone using ScalaJS on the front end. I've seen ClojureScript used like this (as a wrapper for React/Flux architectures), but I wasn't expecting to see ScalaJS.

I'm very new to Scala / Spray (perused the manuals a few years ago, and only came back to it today), but the installation went smoothly today - downloaded Scala and sbt and installed this demo, and it was up and running with no errors.

Other possibly related Scala/Spray projects I also installed today were:

https://github.com/jacobus/s4 (provides a RESTful API to a Postgres backend)

https://github.com/onurzdg/spray-app (implements a simple chat app, including authorization / authentication)

It would be great if you later have time to add a RESTful Postgres back-end and authentication / authorization to this project!

**Comment by ochrons** [comment]
Thanks for your nice comment!

I'm using this project as a "test-bed" for things I'm building in a larger project, so I will be adding many more standard features in the near future.
