### ISSUE TITLE
isomorphic scala.js web apo

### ISSUE THREAD

**Issue by dario-liberman-jav** [ochrons/scalajs-spa-tutorial#9]
This tutorial is awesome, thanks!

Now, with all the effort put into having the MVC written in scala, I wonder, would we not be able to execute the web app server-side too: pre-rendering the view as well as pre-loading the model?
Surely we could have classes in scala that implement React rendering?
We do not need the full app, just the rendering and service URI mapping to pre-execute the first Ajax request (piggybacked at the bottom of the html body).
That way we could use real URLs instead of fragments, speed up the first page (happy mobiles) and support web bot crawlers.

What do you think?

**Comment by tindzk** [comment]
I was thinking about that, too (https://github.com/widok/widok/issues/25). However, it seems like React already provides everything that is needed for server-side rendering. Have a look at this [Gist](https://gist.github.com/koistya/24715d295fbf710d1e24). You could implement an io.js server in Scala.js that does all the server-side rendering. Another approach would be to port those rendering-related parts of React to native Scala code. Then you can serve the rendered HTML directly from the JVM.

**Comment by ochrons** [comment]
For SEO, I would use the `hashbang` system, which is supported by most crawlers. For example http://www.intridea.com/blog/2014/9/18/seo-for-single-page-applications

Use PhantomJS to render the page on the server to HTML, and provide that to the crawlers.

**Comment by dario-liberman-jav** [comment]
I was thinking more in line with porting rendering-related parts of React to native Scala to run on the JVM.
I do not trust headless pre-renderers, I also would like to get the benefit of pre-rendering for everybody, not just crawlers.

**Comment by ochrons** [comment]
Closing this, as it goes way beyond the scope of this little tutorial :)
